### ISSUE TITLE
Move migration scripts to ods-core

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#1]
The migration scripts are not related to the quickstarters. They should work for any kind of OCP project. Therefore, it would be better to move them to ods-core so that the quickstarters repo is smaller (which is good because that is the repo users most likely will have to customize).

Careful: ods-jenkins-shared-library uses them, so it needs to be updated as well.

**Comment by clemensutschig** [comment]
@michealsauter this has impact in rundeck as well.. there is a job referencing this
