### ISSUE TITLE
Support deploying to nexus via maven

### ISSUE THREAD

**Issue by stfnsche** [opendevstack/ods-project-quickstarters#127]
Please provide means to deploy maven artefacts to nexus.

current state:
in pom.xml 
`<distributionManagement>`
`   <snapshotRepository>`
`       <id>os-nexus-snapshots</id>`
`       <name>Snapshots</name>`
           `<url>url to nexus/repository/snapshots</url>`
      `</snapshotRepository>`
      `<repository>`
            `<id>os-nexus-releases</id>`
            `<name>Releases</name>`
            `<url>url to nexus/repository/releases/</url>`
      `</repository>`
 `</distributionManagement>`

maven deploy fails because there is no server entry in settings.xml to match `os-nexus-releases` respectively,  `os-nexus-snapshots` or any server for that matter.

**Comment by clemensutschig** [comment]
@stfnsche  - the quick workaround for this is to use the gradle task for it - that we know works ...

**Comment by stitakis** [comment]
@stfnsche upload to nexus repo is supported by maven. It is not an ODS feature. As reference: ODS have a quickstarter for Spring Boot that uses gradle instead of maven. Anyway... if I´m understand this correctly, I guess you need to add the nexus repository url and user credentials in the settings.xml. Maybe this blog can help you further: https://www.baeldung.com/maven-deploy-nexus

**Comment by clemensutschig** [comment]
@stitakis  - the challenge is the settings.xml is in the slave - only pom.xml is in the project.

so we have to support this in ODS

**Comment by stitakis** [comment]
@stfnsche I´m not sure if understand the problem... btw would solve the problem if you specify the settings.xml in maven command like this "mvn --settings YourOwnSettings.xml clean install" ?

**Comment by stfnsche** [comment]
this would work I guess. although I think it would be nicer if the nexus server would already be defined in the settings.xml from the image. and the ods pipeline would use sed to replace the password and user with $NEXUS_USER respectively $NEXUS_PASSWORD in settings xml before stageBuild is called.

**Comment by clemensutschig** [comment]
We will Fix it globally..  Bit at least you have a Workaround..
