### ISSUE TITLE
Verify Java formatting on Jenkins

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#149]
Given this `build.gradle`:
```
plugins {
    // Code Formatting
    // See https://github.com/sherter/google-java-format-gradle-plugin.
    id 'com.github.sherter.google-java-format' version '0.8'
}
googleJavaFormat {
    toolVersion = '1.6'
    options style: 'AOSP'
}
```

One can check the formatting in Jenkins easily by adding the following stage to the `Jenkinsfile`:
```
def stageCheckFormat(def context) {
  stage('Check Format') {
    withEnv(["NEXUS_HOST=${context.nexusHost}", "NEXUS_USERNAME=${context.nexusUsername}", "NEXUS_PASSWORD=${context.nexusPassword}"]) {
      sh "./gradlew verGJF --no-daemon"
    }
  }
}
```

**Comment by stitakis** [comment]
Hi, I like the idea to provide a default format checker. I tried the solution above and works. The build fails if classes are not formatted according to the google java format. Beside classes that I wrote myself I have in my project classes that are generated. The plugin let you exclude package for such cases with `exclude '**/revinate/demo/*.java'`

**Comment by stitakis** [comment]
@michaelsauter was decided how to deal with wrong format of java classes regarding this options: A. reformatting and commit,  B. build fail if format is incorrect, C. warning is added to the logging?

**Comment by michaelsauter** [comment]
We fail the build.

However, I noticed that `verGF` is part of the `build` task, so no separate step is needed ...

**Comment by michaelsauter** [comment]
As per last comment, no change needed.
