### ISSUE TITLE
Cleanup containers running for a long time

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#17]
If some error occurs and the container is not cleaned up properly, it might continue to run forever. The cleanup job should prevent this.

E.g.
```
docker ps | grep 'day[s]* ago' | awk '{print $1}' | xargs docker rm -f
```

**Comment by clemensutschig** [comment]
this will come as my big rundeck job merge commit

#!/bin/bash

found_dirs=$(sudo find /tmp -name "rundeck_*" -mtime @option.days_to_retain@ -type d)
echo "Directories to delete:"
echo $found_dirs
echo $found_dirs  | xargs sudo rm -rf

echo "Pruning unused Docker data"
sudo docker system prune --force

echo "Pruning running docker containers"
docker ps | grep 'day[s]* ago' | awk '{print $1}' | xargs docker rm -f

cool?
