### ISSUE TITLE
Move check_ocp_secure_routes.sh to ods-core

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#2]
This script is not related to the quickstarters. It should work for any kind of OCP project. Therefore, it would be better to move it to ods-core so that the quickstarters repo is smaller (which is good because that is the repo users most likely will have to customize).

**Comment by clemensutschig** [comment]
Like! The only challenge is that we need a second rundeck project to scm-import from another repo :-(

**Comment by michaelsauter** [comment]
Oh. I was thinking to just point the existing rundeck job to the ods-core repo. But of course, that introduces some nasty coupling plus requires the user to clone the ods-core repo to bitbucket (though, as shared elsewhere, I think this is good/necessary anyway). 

Maybe we should not do the change suggested here until we have figured out the cloning strategy and maybe even have a plan to move the whole rundeck thing into ods-core (which is what I would like to have eventually).

**Comment by michaelsauter** [comment]
Done - see above.
