### ISSUE TITLE
Rshiny quickstarter broken.. required ocp template missing.. (cd//component-pipeline)

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#200]
@henrjk / @michaelsauter  - fyi.

**Comment by clemensutschig** [comment]
As discovered thru #38

**Comment by henrjk** [comment]
This has moved a bit in master.  The reference to template `cd/component-pipeline` which is no longer uploaded is at:  

https://github.com/opendevstack/ods-project-quickstarters/blob/0388907de67e3e72617162719180389b5237e77a/ocp-templates/scripts/create-rshiny-app.sh#L53

**Comment by clemensutschig** [comment]
@henrjk  . fix with the PR attached :)
