### ISSUE TITLE
import metadata: docker pull secrets are not created in an existing project - breaks oc import-image

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-project-quickstarters#202]
In an already existing project, the docker pull secrets are not created - when running import-metadata.sh

Proposed solution:

This [if statement](https://github.com/opendevstack/ods-project-quickstarters/blob/36b6c52714f4da5c04be53925dde1a633027aa26/ocp-templates/scripts/import_ocp_project_metadata.sh#L490) should be executed if the secret does not exists and not only during the creation of new projects

**Comment by clemensutschig** [comment]
https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/import_ocp_project_metadata.sh#L492-L494 - only creates and links in case *new*  project

if this is NOT done .. (and you are not on the same cluster) ...
https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/import_ocp_project_metadata.sh#L657 

fails ...

**Comment by clemensutschig** [comment]
@hugowschneider - you fix this for 1.1-yes?
