### ISSUE TITLE
Dockerfile invalid (ENV instead of RUN)

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-project-quickstarters#208]
That piece of code is invalid as ENV expectes KEY VALUE pair.
Do you want to execute (RUN) `localedef` ?

https://github.com/opendevstack/ods-project-quickstarters/blob/b73bb4a1b9afc6974ca7b055fe1cc7e496a9a741/boilerplates/jupyter-notebook/files/docker/Dockerfile#L12

If `localedef` should be executed then additional packages have to be installed beforehand.

**Comment by clemensutschig** [comment]
@sklingel- can you take this up in the Open pr

**Comment by sklingel** [comment]
@clemensutschig, this will be gone anyway, when the PR is through that moves the image to rhel

**Comment by sklingel** [comment]
Will be done when #213 is approved
