### ISSUE TITLE
custom nexus certificate requires fix e.g. pip install --trusted-host

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-project-quickstarters#209]
If the server has a custom certificate either certificates have to be installed properly (certify+certificate installation) or the host has to be defined as trusted-host using `--trusted-host {NEXUS_URL:8}`
https://github.com/opendevstack/ods-project-quickstarters/blob/b73bb4a1b9afc6974ca7b055fe1cc7e496a9a741/boilerplates/jupyter-notebook/files/docker/run.sh#L25

**Comment by clemensutschig** [comment]
@sklingel- same here

**Comment by sklingel** [comment]
Actually @gerardcl tackled this somehow already, at least for the on-premise Jenkins slave?
But I can also just add the "--trusted host", if we are sure we can always trust it ;-)

**Comment by sklingel** [comment]
Will be done when #213 is approved
