### ISSUE TITLE
sync versions between environments

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-project-quickstarters#210]
Is it expected to have v3.0 also onprem?

https://github.com/opendevstack/ods-project-quickstarters/blob/b73bb4a1b9afc6974ca7b055fe1cc7e496a9a741/ocp-templates/templates/rshiny-app.yml#L144

**Comment by clemensutschig** [comment]
Yes .. See ods-core / shared Images / ocp config/ bc.yml
