### ISSUE TITLE
Allow more control over Jenkins builds

### ISSUE THREAD

**Issue by cschweikert** [opendevstack/ods-project-quickstarters#224]
**Problem**
Currently most of the Jenkins files in the different quickstarters work in a way that will stop a Jenkins run, if something went wrong, e.g. linter errors or one or more failing unit tests. This makes it difficult to e.g. report to SonarQube, since this step usually happens after unit tests, linting, etc.

**Proposal**
Unit tests, Linting, etc. does not fail any more, but the state of those will be collected somehow. ODS supports a function, e.g. called `stageFailOnError()`, that will only fail, if an error state was captured earlier.
This can look like this:
```
odsPipeline(
   ...
) { context ->
  stageBuild(context)                # testing and building
  stageScanForSonarqube(context)     # publish to SonarQube
  stageFailOnError(context)          # maybe die or continue
  stageStartOpenshiftBuild(context)  # continue publishing to OpenShift
  stageDeployToOpenshift(context)
}
```

An explicit function that checks error states allows standardizes error messages about what went wrong in the build chain and give more control over the point in time a build should fail.

**Yet to clarify**
* How to track error states nicely?
* (How) Can a Jenkins build pipeline tell Jenkins properly which step failed and still continue with following steps?

**Comment by michaelsauter** [comment]
Hmm - I think the standard behaviour in Jenkins is to fail and abort if an exit code other than 0 is encountered. I would keep this behaviour.

Alternative suggestions:
1. Add an optional argument to e.g. the build stage to continue on error
2. Just reorder the stages if you want SonarQube checks to always run

What do you think?

**Comment by rattermeyer** [comment]
Agree with Michael. Would keep default behavior. However if a checkin has many issues, they are only sequentially detected, but hopefully this is normally not the case.
For all others it might be an option to reorder the steps.

**Comment by michaelsauter** [comment]
Closing this. @cschweikert if you strongly disagree, please reopen.
