### ISSUE TITLE
be-python-flask build fails

### ISSUE THREAD

**Issue by thowerner** [opendevstack/ods-project-quickstarters#232]
be-python-flask build fails. Need to comment out this build step in Jenkinsfile for successful build:

      // PEP8
      sh '''
         pycodestyle --show-source --show-pep8 src/*
         pycodestyle --statistics -qq src/*
      '''

I assume is because src folder contains also other file types (html, etc.). Perhaps ... src/*.py will work?

**Comment by clemensutschig** [comment]
@thowerner  - 
latest 1.1 (which will go on premise this week) looks minorly different..

https://github.com/opendevstack/ods-project-quickstarters/blob/1.1.x/boilerplates/be-python-flask/Jenkinsfile#L60-L65

can you please paste the error you are getting?

@sklingel - fyi .. and pull in andras ...

**Comment by thowerner** [comment]
[fws-cd-be-python-flask-master] Running shell script
+ pycodestyle --show-source --show-pep8 src/app.py src/requirements.txt src/setup.py src/static src/templates src/test_requirements.txt src/tests.py
src/app.py:13:37: W292 no newline at end of file
app.run('0.0.0.0', 8080, debug=True)
                                    ^
    Trailing blank lines are superfluous.

    Okay: spam(1)
    W391: spam(1)\n

    However the last line should end with a new line (warning W292).
src/requirements.txt:1:6: W292 no newline at end of file
flask
     ^
    Trailing blank lines are superfluous.

    Okay: spam(1)
    W391: spam(1)\n

    However the last line should end with a new line (warning W292).
src/setup.py:4:6: E211 whitespace before '('

**Comment by clemensutschig** [comment]
This is clearly a bug .. @gerardcl  can you take a look, cannot be that the default quickstarter is failing ...

**Comment by gerardcl** [comment]
I will be able to solve the issue once github solves a bigger one --> https://twitter.com/githubstatus/status/1141629836202532864

OMG
