### ISSUE TITLE
Improve "change existing quickstarters" documentation

### ISSUE THREAD

**Issue by ultrasonicsoft** [opendevstack/ods-project-quickstarters#246]
In [README](https://github.com/opendevstack/ods-project-quickstarters
) file - section "Changing existing quickstarters", doesn't mention that we need to fetch GitHub master branch.

It should have consistent steps as per [ODS](https://www.opendevstack.org/doc/development-guide) guidelines.

**Comment by michaelsauter** [comment]
Closing as many things have changed in the meantime and a new guide has to be written anyway.
