### ISSUE TITLE
Add Go quickstarter

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#255]
Quickstarter to develop with https://golang.org, especially useful/suited for CLI tools, network/DevOps related things and small microservices.

**Comment by metmajer** [comment]
@michaelsauter the new quickstarter doesn't show up in the provisioning app yet. Any plans on making it available there? Thanks!

**Comment by michaelsauter** [comment]
@metmajer The provisioning app reads the jobs from Rundeck. Rundeck does not automatically update - first you would need to update the repository in Bitbucket, then import the jobs from Git in Rundeck. Afterwards you should see the new Go quickstarter.

**Comment by metmajer** [comment]
Thanks, @michaelsauter, I'll give it a try.
