### ISSUE TITLE
ds-ml quickstarter (rundeck) provision fails on permissions against init.sh / *.sh

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#267]
11:22:27 | /bin/bash: ./custom-create-components.sh: Permission denied

**Comment by clemensutschig** [comment]
and also build.sh fails during jenkins build

**Comment by gerardcl** [comment]
I checked that and it was only happening on premises, the issue was added due to going through windows machine and bad management of file copies/permissions
closing #267 since I have already set right permissions
