### ISSUE TITLE
jupyter quickstarter app: Kernel won't start

### ISSUE THREAD

**Issue by misza222** [opendevstack/ods-project-quickstarters#268]
Jupyter Lab UI works, but when trying to launch a kernel in the pod's logs we get:
```
[W 11:57:37.318 LabApp] [Errno 13] Permission denied: '/opt/app-root/src/.jupyter/lab'
```

**Comment by clemensutschig** [comment]
@gerardcl - we should Bundle this with the oc Port fwd fix..

**Comment by gerardcl** [comment]
hi @clemensutschig , this is another boilerplate issue not related to ds-ml-service oc port forward issue

**Comment by clemensutschig** [comment]
@gerardcl i know- Just asking whether we should bundle the fixes for the 2 issues

**Comment by gerardcl** [comment]
in terms of changelog we can do so, so to bundle, for example, all DS related fixes/changes in one line. is it aligned on what you are saying?

**Comment by clemensutschig** [comment]
@gerardcl fixed?

**Comment by gerardcl** [comment]
fixed locally in our project, not ready yet in ods, will do so during the week

**Comment by clemensutschig** [comment]
Top! Please also Tag for 1.2

gerardcl <notifications@github.com> schrieb am Sa., 24. Aug. 2019, 18:03:
