### ISSUE TITLE
Python quickstarter should use nexus as artifact repo

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#27]
All other quickstarters point to nexus to retrieve artifacts - except python - this should be change and implemented according to

https://help.sonatype.com/repomanager3/pypi-repositories

pip implementation ... sort of lovely
pypa/pip#4315

**Comment by sklingel** [comment]
closed by #65

**Comment by michaelsauter** [comment]
Actually, this needs to be done for the Python quickstarter, too - not just for Jupyter.

The fix should be similar to #65.

@sklingel Could you apply the same fix?

Also - the Jenkins slaves also need to make use of Nexus.

**Comment by clemensutschig** [comment]
And lastly the getting started guide needs to contain the repo setup

**Comment by michaelsauter** [comment]
@adyachok Is this something you could have a look at? You can see what @sklingel did for Jupyter in #65.

**Comment by clemensutschig** [comment]
@sklingel is this now done?! ..

**Comment by sklingel** [comment]
@clemensutschig for the jupyter yes. @adyachok is working at that, as far as I know

**Comment by clemensutschig** [comment]
@sklingel  @adyachok - is this done now?!

**Comment by michaelsauter** [comment]
This is still in PR internally but pretty much done. Adding to 1.1 (because the 1.0.1 train has passed I'd say).

**Comment by clemensutschig** [comment]
@sklingel  -status?

**Comment by clemensutschig** [comment]
@adyachok - fixed now? can we get this into 1.1.?
