### ISSUE TITLE
docker cleanup fails if no containers

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-project-quickstarters#281]
Hi,

the clean-tmp fails, if we do not find any eligable containers for pruning.
https://github.com/opendevstack/ods-project-quickstarters/blob/98f650ff9e29883b45fcf6f8b83c58ea0a1ec575/rundeck-jobs/common/cleanup-tmp.yaml#L39

**Comment by rattermeyer** [comment]
Easy fix (will provide PR):

-bash-4.2$ docker ps | grep 'day[s]* ago' | awk '{print $1}' | xargs docker rm -f || echo "no containers found"

"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
no containers found

Still gives you the error, but does not fail the job, but prints "no containers found"

**Comment by michaelsauter** [comment]
@rattermeyer Keep in mind that this part will go away in 2.0 once Rundeck is gone ...

**Comment by rattermeyer** [comment]
you are right. but as long as we have rundeck, it is a bug ...
