### ISSUE TITLE
Find solution for secure route checking after Rundeck is gone

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#285]
Please also see #2.

**Comment by kiwo** [comment]
Create Jenkins Job which runs on certain interval?

**Comment by michaelsauter** [comment]
@kiwo Sounds like a viable first approach.

**Comment by gerardcl** [comment]
hi @kiwo , we found out that we also need to check for termination type "Re-encript" (so to assure we check for all possible terminations, now only checking if it is "Edge" or "Passthrough"), we will provide an update in 1.2.x related script soon-ish!
