### ISSUE TITLE
Error building Python based Quickstarters on OKD

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-project-quickstarters#295]
On a standard OKD cluster, the default python based quickstarters, like
jupyter-notebook and ds-ml-service are not building, because of certifcate issues:

```
build.build.openshift.io/ds-ml-service-training-service-1 started
Receiving source from STDIN as archive ...

Pulling image registry.access.redhat.com/rhscl/python-36-rhel7 ...
error: build error: failed to pull image: open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory.
```

**Comment by rattermeyer** [comment]
Actually, on OKD the python image is based on `docker.io/centos/python-36-centos7:latest`.
On other occasions, we can override the Dockerfile FROM line in the buildconfig with a reference to the image stream (which then can be converted to the correct image reference in a registry).

So, as we provide installation steps for OpenDevStack based on OKD, we should aim that all quickstarters directly work in the "OpenSource" version.

An option would be to include two `FROM` lines (centos and redhat) and a README describing how to replace it globally (in the production branch) or locally (in each project).

Any comments?

**Comment by clemensutschig** [comment]
@gerardcl @hugowschneider

**Comment by hugowschneider** [comment]
@rattermeyer, I need to double check, but I understand that redhat images can only be pulled from a OpenShift cluster.

To fix it the Dockerfile needs to be changed to a centos based python image for example:
```
FROM centos/python-36-centos7
```

I will double check the impact of this change, please let me know if it worked for you

**Comment by rattermeyer** [comment]
Yes, with this change, it is working.

**Comment by gerardcl** [comment]
added solution for jupyter-notebook :)
