### ISSUE TITLE
Enable xml unit - unit test results on all quickstarters and refactor build stage 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#299]
for the MRO implementation we expect quickstarters to dump unit test results as xml unit (junit compatible) files.

All quickstarters should enable that - and split the build stage into a real build Ans a real Unit test stage. This will also help for mro

**Comment by clemensutschig** [comment]
they should either go into `build/test-results/test` directory OR set the new property in the ods pipeline config `testResults` pointing to the directory 

```
odsPipeline(
  ...
  testResults : 'build/test-results/test'
  ... 
) { context ->
  ... 
}
```

**Comment by clemensutschig** [comment]
@akhilsoman  @stitakis  @hugowschneider  @oalyman @ManuelFeller @m-apsolon

**Comment by michaelsauter** [comment]
For Go, I propose to use https://github.com/jstemmer/go-junit-report.

**Comment by clemensutschig** [comment]
for details on where to put refer to opendevstack/ods-jenkins-shared-library#108 - either into the std location, or overwrite it by setting `testResults` in the shared lib config

**Comment by michaelsauter** [comment]
* @bljubisic will take care of the NPM based quickstarters
* @oalyman will fix the Scala quickstarter as it does not build out-of-the-box right now, and then add the junit support
* I will take care of `be-golang`
* @gerardcl could you do this for the Python based ones?

**Comment by clemensutschig** [comment]
@stitakis  - can you do the spring boot qs?

**Comment by clemensutschig** [comment]
@stitakis  - can you do the spring boot qs?

**Comment by michaelsauter** [comment]
I think spring boot does that by default already ...

**Comment by bljubisic** [comment]
I will do the same of what I have done with angular on ionic

**Comment by gerardcl** [comment]
all jupyter related ones DONE (jupyter-notebook is not having it since as far as of now it is not having any build/test stage, only deployment of the tool), so jupyter related changes were applied to be-jupyter-flask and ds-ml-service
