### ISSUE TITLE
Move jenkins templates to ods-core

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#3]
They should not need to be customized and are better located in ods-core.

**Comment by clemensutschig** [comment]
@michaelsauter  - this would require tailor to support upload-templates :)

**Comment by michaelsauter** [comment]
FYI @kiwo

**Comment by rattermeyer** [comment]
Not completely convinced yet. Because this will grow core with every new slave.
Probably depends what we define as core:

* Everything that does not need to be customized (then it could be moved there)
* Foundation for all further functionality provided by ODS (then I wouldn't put it there)

**Comment by michaelsauter** [comment]
@rattermeyer I think there is a misunderstanding.

I want to:

* have everything that is related to "project provisioning" in ods-core
* have everything that is related to "component provisioning" in ods-project-quickstarters (which we could rename to ods-quickstarters)

That way we have a clean separation, and we pave the way to multiple "quickstarter repos", e.g. ones that only exist within an organisation on BitBucket with private quickstarters.

I am not proposing to have the slaves in core, just the master templates ...

**Comment by michaelsauter** [comment]
Done as part of https://github.com/opendevstack/ods-core/pull/227, and further refinement is in https://github.com/opendevstack/ods-core/pull/241. The new `ods-quickstarter` repo does not have the templates anymore since https://github.com/opendevstack/ods-quickstarters/pull/3.
