### ISSUE TITLE
Command "export" is deprecated, use the oc get --export

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-project-quickstarters#317]
update oc cli commands used on scripts to not get deprected messages and wrong behaviours

also related to issue: https://github.com/opendevstack/ods-jenkins-shared-library/issues/109

**Comment by michaelsauter** [comment]
I think this might get removed completely in 4.1, need to check that.

**Comment by gerardcl** [comment]
then we just keep it as it is for now? I will wait answer from your check!
I am just popping this issue since the script seems not fully work 100%, might still be related to SA and rolebindings...

**Comment by gerardcl** [comment]
for now I just can confirm that the deprecated export command behaves different, for sure it gets less data... and that might be the issue we are facing now

**Comment by michaelsauter** [comment]
Yes the behaviour is different. I just know that export is using something from upstream Kubernetes, and that is going to be removed so OpenShift is following suit. 

I think we need to tackle this issue soon - once there is an easy way to install Openshift 4.1 locally to play around with it and see what breaks.
