### ISSUE TITLE
Handling of Gradline in slave-maven

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-project-quickstarters#326]
Maven is installed in the slave. Comments say: Install gradle, but only the gradle wrapper is installed. Not sure what the intention of the author was, but currenlty it is not a correct solution.

Proposal: We should install gradle completely and put it on the path.
This offers two options for developers

* Either use the gradle wrapper and have complete control of the gradle version for your project (but resulting in longer build times, because gradle is downloaded for every build)
* Use the "standard" gradle version provided with the slave. Which results in shorter build times, but you are bound to the gradle version provided (and your build might break when the slave is updated)

**Comment by clemensutschig** [comment]
gradlew version should download gradle thru the wrapper.. did you Check Re build logs?

**Comment by rattermeyer** [comment]
indeed it does pull it down. I saw it download gradle again. But this was a shortsight: installed was version 5.6.1, the project used 5.4.1, so the behavior is correct... check with matching versions. and then we should document that.

**Comment by rattermeyer** [comment]
Works as expected.

**Comment by michaelsauter** [comment]
So we can close?

**Comment by rattermeyer** [comment]
yes
