### ISSUE TITLE
Rundeck jobs should allow configuration of used  ods-project-quickstarter branch (and not hardcode "production")

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#33]
reason being that people want to play around - and while this is possible thru changing a bc's reference to a branch - rundeck jobs hardcode checkout -b production

@tjaeschke  - fyi :)

**Comment by clemensutschig** [comment]
@michaelsauter - thoughts? I plan on "just" making the branch configurable thru a global project property ... the big question is if we don't introduce it only on the quickstarts and NOT on common and openshift (as they should be really really stable)

**Comment by michaelsauter** [comment]
I think the easiest recommendation would be to "clone the job". If you have a variable for the branch to use, then by changing that variavble you immediately affect others because the job you are trying to test is effectively modified, right?

**Comment by clemensutschig** [comment]
@michaelsauter - ok that means we leave the setup .. which is 2 branches that you need to touch. Currently rundeck jobs live from *rundeck-changes* (branched off master) - and a running instance of a jobs grabs *production* .. I am not sure this the most sustainable way.. (maybe switch both to use production branch? wdyt?

**Comment by michaelsauter** [comment]
@clemensutschig My comment was only regarding the configurability of a branch different than production, which is not needed IMHO. The other issue with the two branches rundeck-changes and production is different I think, and I yes, I would agree that we could try to push rundeck commits directly into production. Would be more consistent ...

**Comment by michaelsauter** [comment]
@clemensutschig Can this be closed? I would say hardcoding the branch is OK as it is possible to clone the job and do adjustments there.

**Comment by clemensutschig** [comment]
Ok closing- we leave as is
