### ISSUE TITLE
generated Spring Boot Quickstarter code does not compile locally

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-project-quickstarters#332]
The documentation states that one have to manually create an `gradle.properties` to define nexus related properties.

If those properties are not defined (Eighter by enviroment variables or properties), the  build does not succed:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Failed to notify dependency resolution listener.
   > Could not resolve all dependencies for configuration ':detachedConfiguration1'.
      > Authentication scheme 'all'(Authentication) is not supported by protocol 'file'
   > Could not resolve all dependencies for configuration ':detachedConfiguration2'.
      > Authentication scheme 'all'(Authentication) is not supported by protocol 'file'
```

The specificatin of those properties is fine if nexus is needed. If not needed, the build should compile without any further action. Specification of gradle.properties should be optional in this case. Dependencies can be downloaded from jcenter and mavenCentral.

**Comment by rattermeyer** [comment]
Can we handle it in the quickstarter, the same way it works for the provisioning app (no_nexus property)?

**Comment by stefanlack** [comment]
Yes, but we do not need to specify no_nexus property at all:

```
buildscript {
    ext
            {
                nexus_url = "${project.findProperty('nexus_url') ?: System.getenv('NEXUS_HOST')}"
                nexus_user = "${project.findProperty('nexus_user') ?: System.getenv('NEXUS_USERNAME')}"
                nexus_pw = "${project.findProperty('nexus_pw') ?: System.getenv('NEXUS_PASSWORD')}"
                nexus_folder = "${project.findProperty('nexus_folder') ?: System.getenv('NEXUS_FOLDER')}"
                nexus_folder = nexus_folder == "null" ? "candidates" : nexus_folder
                no_nexus = nexus_url == "null" || nexus_user == "null" || nexus_pw == "null"
                if (no_nexus) {
                    println("Do not use nexus, since at least one of properties nexus_url, nexus_user or nexus_pw is not configured")
                }
                snippetsDir = file('build/generated-snippets')
            }
}
repositories {
    if (no_nexus) {
        jcenter()
        mavenCentral()
    } else {
//...
}
```

**Comment by stitakis** [comment]
Hi @stefanlack, I´m not really convinced about not failing the build if any nexus property is missing is a good idea. One reason why companies uses an artifcat repository like Nexus is reproducibility. This guarantees that software can be build even in case an artifact can´t be located in internet.

**Comment by stefanlack** [comment]
I close this issue. The build should realy fail if nexus properties are not defined correctly.

However, in this case the build should print some helpfull error messages. I will implement better error messages in the PR for #330
