### ISSUE TITLE
import of images into other cluster fails - because of missing role for default user

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#345]
https://github.com/opendevstack/ods-project-quickstarters/blob/17e530e7b623625bce38933c5ed242462cd7166e/ocp-templates/scripts/import_ocp_project_metadata.sh#L503

oc adm policy add-role-to-user **system:image-builder** -n awi01-prod  -z default

**Comment by clemensutschig** [comment]
@hugowschneider  @rattermeyer  - see above, this should be a quick fix ..

**Comment by clemensutschig** [comment]
@henrjk - can you fix this one as well Please?

**Comment by henrjk** [comment]
@clemensutschig  do you mean it like this:

https://github.com/BIX-Digital/ods-project-quickstarters/commit/ef20a943953e22fe6927adb1b141db7f3d41e81d

**Comment by clemensutschig** [comment]
same needs to go into 
https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/create-projects.sh#L68
