### ISSUE TITLE
export-ocp-config exports always an entire namespace - need way to pass specific components only

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#384]
**Is your feature request related to a problem? Please describe.**
https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/export_ocp_project_metadata.sh#L113 does not allow you to pass a list of component names, which we need for the MRO export

**Describe the solution you'd like**
be able to pass a list of component names, and only those are exported.

**Describe alternatives you've considered**
none, no workaround

**Comment by michaelsauter** [comment]
@clemensutschig We really need to think about how we want to solve this for 2.0. Tailor already supports this use case ...

**Comment by clemensutschig** [comment]
@michaelsauter  - be my guest .. I just said, we need a way to specify ... if that means we switch full scale to tailor .. I leave to my loved engineering team :)

**Comment by michaelsauter** [comment]
I guess we can close this now.
