### ISSUE TITLE
Go quickstarter fails with no tests when collecting test results via junit

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#388]
**Describe the bug**
The initial build of the Go quickstarter fails. This is because there are no tests after provisioning, but the MRO stuff expects some tests.

Failure is:
```
Recording test results
None of the test reports contained any result
```

**To Reproduce**
Provision a new Go quickstarter and watch the Jenkins pipeline.

**Expected behavior**
The first build should be successful

**Affected version (please complete the following information):**
 - OpenShift: all
 - OpenDevStack: master

I suggest to add a dummy test into the quickstarter.

**Comment by metmajer** [comment]
I think the problem is less on the MRO side, but because the call to `junit` inside the component may not accept an empty (undefined) argument.

**Comment by michaelsauter** [comment]
@metmajer Ah, could be! Oh well ... the "fix" solves it anyway :)
