### ISSUE TITLE
mro release manager quickstarter contains wrong readme!

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#395]
**Describe the bug**
readme.md of release manager is wrong (shows BE docker plain)

**To Reproduce**
go to https://github.com/opendevstack/ods-project-quickstarters/blob/master/boilerplates/release-manager/README.md

**Expected behavior**
correct readme md content is shown

**Comment by metmajer** [comment]
Resolved by https://github.com/opendevstack/ods-project-quickstarters/pull/396.
