### ISSUE TITLE
Add gitattributes to quickstarters to support multi-platform development

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-project-quickstarters#415]
**Is your feature request related to a problem? Please describe.**
When developers work on different platforms (Windows / Linux) line ending in git can easily become a problem.

**Describe the solution you'd like**
Having a default .gitattributes in every created bitbucket repo, as proposed by [github](https://help.github.com/en/articles/configuring-git-to-handle-line-endings#per-repository-settings)

**Describe alternatives you've considered**
Rely on configuration of the clients, as described by [github](https://help.github.com/en/articles/configuring-git-to-handle-line-endings#global-settings-for-line-endings).
But this is not reliable (if someone forgets about this)

**Comment by metmajer** [comment]
@rattermeyer @michaelsauter also, there are a lot of indentation inconsistencies, which makes it less joyful to read. Have you considered [EditorConfigs](https://editorconfig.org) already? I have recently added one to https://github.com/opendevstack/ods-mro-jenkins-shared-library/blob/master/.editorconfig.

**Comment by michaelsauter** [comment]
@metmajer `.editorconfig` does not hurt, but IMHO for a project like ODS with so many contributors we need to check in Travis ...

**Comment by metmajer** [comment]
Yes, it’s only a first line of defense on a developer‘s machine. Have you considered using pre-commit hooks for syntax checking?

**Comment by michaelsauter** [comment]
@metmajer I don't know of any pre-commit hooks in place or even considered. But I like the idea (we use it as well in our initiative), we should add this to at least provide support for those that don't want to see their commits fail in CI :)

**Comment by rattermeyer** [comment]
Pre-Commit hooks are also in the hand of the developers, because they life in .git/hooks. 
We could however consider something like [git-hooks/git-hooks](https://github.com/git-hooks/git-hooks) to provide per-repository git-hooks.
