### ISSUE TITLE
jupyter-notebook fails to deploy if secret is already available

### ISSUE THREAD

**Issue by alistairlenhard** [opendevstack/ods-project-quickstarters#419]
**To Reproduce**
1. create the jupyter notebook from the boilerplate via provisioning app if a previous project already existed which defined the secrets "crowd-service" in openshift.

**Expected behavior**
1. jupyter note book is created

**Log Output**
2019/10/25 05:59:34 Update aborted: Error from server (AlreadyExists): error when creating "STDIN":
secrets "crowd-service" already exists

In addition: jupyter notebook is not created if the name contains upper case values. If that could at least be outlined in the readme file, it would help to prevent future incorrect deployments as the provisioning app allows for upper case namings.

**Comment by michaelsauter** [comment]
@henrjk Just looking at it with @gerardcl. The issue is the scope: if you tell Tailor to only look at resources with a certain label, then it will not look at resources without that label. BUT if it then executes `oc create`, the created resource might already exist (because for resource identity, only the name matters, not the labels).

**Comment by alistairlenhard** [comment]
just another hint: if I remove the secret, rundeck seems to progress further. So my project on dev seems to be created on openshift. Now the same error would appear on [project]-test. 
Do you know when the bitbucket resources are filled in this process? Currently it seems like they remain empty until both openshift dev and test are created and only then the code is pushed? I am saying this because the login to the jupyter notebook on openshift now also does not work and it does not really seem to have all sources on openshift yet for dev.

**Comment by henrjk** [comment]
@alistairlenhard The secrets that have been created originally: did they come from a quickstarter create with a prior ODS release?

Perhaps the label should be removed for the secrets?

**Comment by gerardcl** [comment]
hi @henrjk  I confirm that jupyter was before 1.2.x
