### ISSUE TITLE
Freshly created spring boot project does not compile

### ISSUE THREAD

**Issue by bitkid** [opendevstack/ods-project-quickstarters#440]
**Describe the bug**

When i create a new spring boot project the initial jenkins build fails.

: error: package org.junit.jupiter.api does not exist
import org.junit.jupiter.api.Test;
                            ^
DemoApplicationTests.java:9: error: cannot find symbol
	@Test
	 ^
  symbol:   class Test
  location: class DemoApplicationTests
2 errors

**Comment by stefanlack** [comment]
The quickstarter generates a junit 5 based test. Configured libraries do not match to test. 


Quickfix - Fix test implementation on generated code
```
import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;
@SpringBootTest
public class DemoApplicationTests {
  @Test
  public void contextLoads() {
  }
}
```

Quickstarter has to be corrected.

**Comment by michaelsauter** [comment]
@stefanlack @stitakis @hugowschneider @adyachok  Anyone willing to look into this? Be aware though that the new quickstarters are in `ods-quickstarters` repo and fix would need to go there as well.

**Comment by stefanlack** [comment]
I am going to create a bug fix on next monday.

@michaelsauter , @clemensutschig wich junit version should be used?

**Comment by michaelsauter** [comment]
@stefanlack Spring Boot 2.2.0 (latest version) ships with Junit 5 by default ... so it should be Junit 5 I think.
