### ISSUE TITLE
Link to Quickstarters documentation is broken

### ISSUE THREAD

**Issue by smolanet** [opendevstack/ods-project-quickstarters#450]
**Describe the bug**
The link that points to OpenDevStack Quickstarters documentation is broken.

**To Reproduce**
1. Go to https://github.com/opendevstack/ods-project-quickstarters/blob/master/README.md
2. Click on OpenDevStack Quickstarters
3. See error

**Comment by michaelsauter** [comment]
This repo is no longer in use since ODS 2. I've made this more clear now in the readme:

> CAUTION! This repo is DEPRECATED. For ODS 2+, please see ods-quickstarters repository.
