### ISSUE TITLE
python slave lates fails with compilation error

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#47]
start-build jenkins-python-slave:

File "/tmp/Python-3.7.0/Lib/ensurepip/__init__.py", line 27, in _run_pip
--
  | import pip._internal
  | File "/tmp/tmpoawgt5mu/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/__init__.py", line 42, in <module>
  | File "/tmp/tmpoawgt5mu/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/cmdoptions.py", line 16, in <module>
  | File "/tmp/tmpoawgt5mu/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/index.py", line 25, in <module>
  | File "/tmp/tmpoawgt5mu/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/download.py", line 39, in <module>
  | File "/tmp/tmpoawgt5mu/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/utils/glibc.py", line 3, in <module>
  | File "/tmp/Python-3.7.0/Lib/ctypes/__init__.py", line 7, in <module>
  | from _ctypes import Union, Structure, Array
  | ModuleNotFoundError: No module named '_ctypes'
  | make: *** [altinstall] Error 1
  | Removing intermediate container e02548dcffe3
  | error: build error: The command '/bin/sh -c set -x     && INSTALL_PK

**Comment by clemensutschig** [comment]
https://bugs.python.org/issue31652

**Comment by michaelsauter** [comment]
@adyachok could you have a look?
