### ISSUE TITLE
nodejs slave build fails with nexus exposed via edge ssl route

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#48]
oc start build jenkins-slave-nodejs8-angular

npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
--
  | npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
  | npm ERR! request to https://... xxxx .... /repository/npmjs/@angular%2fcli  failed, reason: self signed certificate in certificate chain

https://stackoverflow.com/questions/9626990/receiving-error-error-ssl-error-self-signed-cert-in-chain-while-using-npm

**Comment by clemensutschig** [comment]
ca=null did not do the trick
strict_ssl=false did it ... 

I have a local branch with this as fix,.. but this sounds to me plain wrong - there must be a way to include the trust.crt from the slave!

**Comment by tjaeschke** [comment]
Found an article on the official npm blog:

https://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more

but I will have to take a deeper look
