### ISSUE TITLE
spring boot quickstarter fails behind proxy

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#58]
16:19:13 | Oct 23, 2018 2:19:13 PM org.apache.http.impl.execchain.RetryExec execute
-- | --
16:19:13 | INFO: Retrying request to {s}->https://start.spring.io:443
16:23:27 | Oct 23, 2018 2:23:27 PM org.apache.http.impl.execchain.RetryExec execute
16:23:27 | INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://start.spring.io:443: Network is unreachable (connect failed)
16:23:27 | Oct 23, 2018 2:23:27 PM org.apache.http.impl.execchain.RetryExec execute
16:23:27 | INFO: Retrying request to {s}->https://start.spring.io:443
16:27:42 | Oct 23, 2018 2:27:42 PM org.apache.http.impl.execchain.RetryExec execute
16:27:42 | INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://start.spring.io:443: Network is unreachable (connect failed)

**Comment by tjaeschke** [comment]
I was a little bit confused by the 0 0 0 0 0 0 0 0, but now I have it. You have shortened the output, right?

` % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                             Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 `

Do you know which user is running the command? Maybe the expectation is not met, that it is 1001.
