### ISSUE TITLE
Rundeck jobs require master branch to be present

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#61]
Although only production and rundeck-changes should suffice - git checkout fails

**Comment by clemensutschig** [comment]
git clone ${globals.bitbucket_sshhost}/opendevstack/ods-project-quickstarters.git

15:46:31 | Cloning into 'ods-project-quickstarters'...
-- | --
15:46:31 | warning: remote HEAD refers to nonexistent ref, unable to checkout.

**Comment by michaelsauter** [comment]
It looks like that `HEAD` is pointing to `master`, which does not exist. See https://stackoverflow.com/questions/11893678/warning-remote-head-refers-to-nonexistent-ref-unable-to-checkout.

So instead of doing e.g.
```
cd /tmp/rundeck_${job.id}_${job.execid} && git clone ${globals.bitbucket_sshhost}/opendevstack/ods-project-quickstarters.git && cd ods-project-quickstarters && ls -la && cd ocp-templates && git checkout -b production origin/production
```

We need to do:
```
cd /tmp/rundeck_${job.id}_${job.execid} && git clone ${globals.bitbucket_sshhost}/opendevstack/ods-project-quickstarters.git && cd ods-project-quickstarters && git checkout -b production origin/production && cd ocp-templates
```

**Comment by michaelsauter** [comment]
... and while we're at it, we can probably remove the `origin/production` since `production` of a freshly cloned repo should already be up-to-date and we don't care about any tracking information.

**Comment by clemensutschig** [comment]
@michaelsauter agreed!

**Comment by clemensutschig** [comment]
@michaelsauter- so you take this up?

**Comment by michaelsauter** [comment]
@clemensutschig Waiting on your approval in our BitBucket instance :)
