### ISSUE TITLE
Quickstarter: Promoting images through different environments / release manager 

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-project-quickstarters#62]
As customers asked for it: It might be interesting to have a quickstarter that only setups a pipeline and ocp environments and shows how to "promote" a docker image through various ocp environments on the same cluster. This is similar to the [Guide](https://docs.openshift.com/container-platform/3.3/dev_guide/application_lifecycle/promoting_applications.html), but already with an opinonated  pre-configured pipeline.

**Comment by clemensutschig** [comment]
@rattermeyer- so rather than build dir each env ist build dir dev and move then?

**Comment by henrjk** [comment]
I noticed in a current project that a component's image build for the dev environment is not 'simply' promoted when it is moved to later stages (environments) such as test, uat and prod. 
Instead there are branches associated with these and 'promotion' is done via pull request which triggers a new build to happen. It would be much better if we used the exact same bits when testing in the various stages.

In the guide mentioned above by @rattermeyer various approaches are sketched to implement image promotion. I'd be happy to start looking into this and/or whether there would have to be additional support in the opendevstack tooling. 

@michaelsauter pointed me to a recent change where image tagging is used to get an image across projects in [clone-project.sh](https://github.com/opendevstack/ods-project-quickstarters/blob/1245dc9f77cea3569340c9ec25f461e7f1d03eec/ocp-templates/scripts/clone-project.sh#L114)

**Comment by stitakis** [comment]
Hi, currently we are using PRs to promote staging of versions. The merge of PR triggers the build pipeline in jenkins. If we reuse the image, which I believe is a good idea, then we will not use PRs for staging versions... so one thing that we will need to solve is how to trigger the build pipeline.

**Comment by michaelsauter** [comment]
@henrjk Sounds good!

@stitakis Yes, the workflow needs to be discussed. In fact, if you simply promote images, then there is no (technical) need for a `uat` or `production` branch (or however you name them).

One thing I wanted to add is that part of the puzzle could also be some kind of manifest which records which versions (images) run in which env ...

**Comment by stitakis** [comment]
just an idea... counting that we have nw in each *-cd projects the webhook-proxy... would be a kind of "Release Manager" screen in the ProvisioningApp something that we could develop to manage staging of versions (and tagging them, and creating a 4 eyes check flow). The "Release Manager" could post request to webhook-proxy to trigger image promotion

**Comment by clemensutschig** [comment]
@michaelsauter - this is one for the jenkins shared pipeline I guess - we couldhave a flag, that either tags or rebuilds, both is already actively in used (tagging in the clone env scripts used by the shared library)

**Comment by michaelsauter** [comment]
@clemensutschig Yes, the lib could do it, but I'm not sure one would even want to run a pipeline? E.g. if you have built an image in a staging environment from e.g. the `staging` branch, then, if you just want to promote that image to production, you don't need to touch the code at all, and consequently you would not follow the normal BitBucket->Jenkins->OpenShift flow. All you need to do is to re-tag.

**Comment by clemensutschig** [comment]
@michaelsauter  - because then you get all the documentation generated later :)

**Comment by michaelsauter** [comment]
@clemensutschig Okay, then we can take it as a requirement to do the re-tagging through Jenkins. Just need to figure out if this will be a manual pipeline, or if there is some magic file or so which records the production image tag.

**Comment by stitakis** [comment]
@all I see promoting images as part of the release process. I assume that an image contains all required stage configuration. One could trigger the promotion of an image let say from master to UAT after setting labeling/tagging master. Unfortunatelly bitbucket does not have a webhook for this and it wouldn´t provide 4 eyes check like PRs do.
Coming back to release process, which for me is more work than just promoting an image to next stage. Imagine you need to update a DB schema and rollback if something when wrong. I have now this idea of creating a special pipeline for release management. This special pipeline would be part of a special  project called "release-manager". Releases could be configured by the devs by setting in a config or script file which version of which components should be deployed to a specific environment. This would have the benefit that one could control/script the release process and get is reviewed in PR and execute by Jenkins.
Sounds good? Your thoughts?

**Comment by henrjk** [comment]
I like Sebastians proposal. I am reiterating how I understand this:

- A dedicated release-manager project would be used for promotions. This project would be work for one initiative. 
- Presumably a quick-starter for the release-manager would be available but each initiative can add extra configuration such as what environments are supported and behavior if needed in certain hooks for example to deal with DB schema updates.
- Promotions would become PRs against the release-manager project and so the team could use the normal process to adopt these and also the promotions would be manifested in version control. 

@stitakis Was this how you meant this?

@All Does it make sense to you as well?

**Comment by clemensutschig** [comment]
Dear all, I don't think we need a dedicated RM quickstarter or magic...
The shared library should account for that - e.g. if you merge a PR into master - the env can be cloned - and an existing env upgraded with that - including any fwd tagging (which is exactly how the library works today for a new branch btw :))

As a whole env is scope of a "migration" -> "move to production, or any other environment" - and there is actually a hook for this ... 

![image](https://user-images.githubusercontent.com/40628552/53571200-9ab98d80-3b68-11e9-823d-ab2bcf81380f.png)

that we seed by default - this should not be hard to do ... (we would know if's a merge and could check if the images exist with that commit hash ..) ...

maybe I don#t understand the issue - so please help me understand it better .

**Comment by henrjk** [comment]
My main goal would be that if one wants to promote (some images) from one environment to the next that no rebuilding happens. Reasons are:
1. Avoid the possibility that a rebuild might actually have a different outcome. For example because some tests are flaky, because some supposedly immutable dependencies are being patched or something sporadic happening. 
2. Rebuilding takes time unnecessarily. 

Being able to have promotions of components be handled similar to a PR review makes sense to me as well. 

@clemensutschig Can this be accomplished already with just shared library or are you suggesting to build something into the shared library to make this work?

**Comment by clemensutschig** [comment]
en large this can be done today (it's done every time when autocreate in the shared lib is set to true). :)

**Comment by michaelsauter** [comment]
I am not convinced that we need a full-blown release manager. I think we might find a way that is less heavy, and therefore works well in both high-speed environments and more regulated environments.

I like the idea of having "PR all the way through", but maybe the shared lib can be smart enough to re-tag an image if rebuilding is not necessary.

**Comment by stitakis** [comment]
Hi all, I found a hook for tags... it seems that bitbucket provides this as post webhook for the event "Tag Created" (Repository Settings: Post Webhooks -> add nwe webhook -> Repository events: "Tag Created")

The problem with triggering an image promotion on tagging event it is that a there is not 4 eyes check, which actually a PR provides. 

In PSP project, we used branches UAT and PROD and promoted versions using PRs, which causes to build a new image for each branch.

Now a new idea: a different approach could be to have a special configuration in project for the "release management". There we could define which version (GIT_TAG or IMAGE_TAG) will be deployed to an environment. ie { uat: v1.5.0, prod: v1.0.0 } Changes to this will need to be done with PR. The shared-lib could be extended for this new logic. Sounds better? :-)

**Comment by michaelsauter** [comment]
@stitakis Theoretically, this could be done as a simple env file, which is supplied to the OCP resource templates. In our project, we have a `ocp-config` repo, which contains all the OCP resources for a namespace. We could simply change the configured image tags there, which would be a PR and then a deployment ....

**Comment by stitakis** [comment]
@michaelsauter sounds good to me... then the ocp-config repo would be the "release-manager" repo, right? How will the deployment work? Do you have already something in place that triggers the deployment?

**Comment by michaelsauter** [comment]
Sorry no, that is just a thought I have but nothing finalised how it would work. The simplest thing would be triggering by commit, and the commit just changes the image tags that should be deployed ...

**Comment by michaelsauter** [comment]
This is now available via https://www.opendevstack.org/ods-documentation/opendevstack/3.x/jenkins-shared-library/orchestration-pipeline.html.
