### ISSUE TITLE
Add Jenkinsfile to jupyter-notebook and rshiny

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#66]
Instead of using a direct webhook, it would be better to use Jenkins for all build actions.

In the case of jupyter-notebook and rhsiny, Jenkins would just do a checkout and trigger a build ...

**Comment by michaelsauter** [comment]
@clemensutschig I think we can/should include this for v1. It is low risk IMHO. 

Personally, I would like to include the webhook proxy for v1. If we do that (and all work for that is done and ready to be reviewed), then this PR is a must.

**Comment by clemensutschig** [comment]
@michaelsauter cool.
