### ISSUE TITLE
Should we remove the be-database quickstarter?

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#75]
It looks like a dummy quickstarter - the `Dockerfile` does not work, and the `Jenkinsfile` looks very old and probably does not work either.

**Comment by clemensutschig** [comment]
@michaelsauter  - I believe we should fix it - so you can spinup a pgres easily ... (w/o catalog) .. thoughts?

**Comment by michaelsauter** [comment]
@clemensutschig I agree that we should provide sth like this. However, the current state is quite broken, and I think to make it work properly, we need to change a few things. For example, we really should use a different OCP template that creates e.g. a PVC. Since other quickstarters also require some specialised OCP template, we need a general solution for this.

With this and the timeline for v1 in mind, I suggest we delete be-database for the v1 release, and bring it back later, but properly.

**Comment by clemensutschig** [comment]
@michaelsauter  - I think we should fix it- otherwise you are bound to use catalog ...

**Comment by michaelsauter** [comment]
@clemensutschig Sorry to bring this up one more time, but ... what exactly is the advantage of using the quickstarter over using the catalog? We used the catalog, and I think this fine to start with.

**Comment by clemensutschig** [comment]
@michaelsauter- agreed then
