### ISSUE TITLE
Quickstarter for binary artifacts (e.g. war deployment)

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#86]
Right now all quickstarters build from source. It would be great to have a quickstarter that simply takes an artifact from Nexus and deploys that (e.g. for environments where the development happens elsewhere, and the delivery of the development is - for example - a WAR file that needs to be deployed).

**Comment by clemensutschig** [comment]
this is pretty standard s2i functionality ... @torstenhe has done sth there already

**Comment by clemensutschig** [comment]
@michaelsauter - this is fixed by #97 no?

**Comment by michaelsauter** [comment]
@clemensutschig Agreed #97 is a good fix for the issue here, too.
