### ISSUE TITLE
Import script fails during import of catalog based images of OpenShift / rhscl namespaces

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-project-quickstarters#98]
When running the import script (import_ocp_project_metadata.sh), it tries to import all image streams to the target cluster including default images, such as Postgres and MariaDB. Importing default images to the target cluster always fails with the following error messages:

```
! error: Import failed (Unauthorized): you may not have access to the Docker image "registry.example.com/rhscl/mariadb-102-rhel7:latest"
       Less than a second ago
error: tag latest failed: you may not have access to the Docker image "registry.example.com/rhscl/mariadb-102-rhel7:latest"
```
```
! error: Import failed (Unauthorized): you may not have access to the Docker image "registry.example.com/rhscl/postgresql-96-rhel7:latest"
     Less than a second ago
error: tag latest failed: you may not have access to the Docker image "registry.example.com/rhscl/postgresql-96-rhel7:latest"
```

A suggested behavior would be ignore all default images based on the name convention.

**Comment by clemensutschig** [comment]
Great Catch. This a Regression for. The earlier version i guess where this worked w/o issues. I Think skipping based in namespace is the best Option we have.

**Comment by clemensutschig** [comment]
I talked with Hugo about this - the best way is to have it configurable thru an entry in
https://github.com/opendevstack/ods-configuration-sample/blob/master/ods-project-quickstarters/ocp-templates/scripts/ocp_project_config_target 

this way - as the env is anyway proprietary to the user - the user gets full control.

@michaelsauter  @hugowschneider  - thoughts?

**Comment by michaelsauter** [comment]
@clemensutschig I think we can also backport that to the 1.0.x branch, right? It's just a bugfix and since you added a fallback in the script, no update is required ...

**Comment by clemensutschig** [comment]
@michaelsauter - see #102  :)
